apiVersion: v1
kind: Service
metadata:
  name: graphql-api
  labels:
    app: graphql-api
spec:
  type: LoadBalancer
  selector:
    app: graphql-api
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-api
  labels:
    app: graphql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: graphql-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app : graphql-api
        frontend: graphql-api
    spec:
      containers:
        - name: graphql-api
          image: graphql-api
          imagePullPolicy: Never
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP