apiVersion: v1
kind: Service
metadata:
  name: graphql-vue
  labels:
    app: graphql-vue
spec:
  type: LoadBalancer
  selector:
    app: graphql-vue
  ports:
  - port: 81
    targetPort: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-vue
  labels:
    app: graphql-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: graphql-vue
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app : graphql-vue
        frontend: graphql-vue
    spec:
      containers:
        - name: graphql-vue
          image: graphql-vue
          imagePullPolicy: Never
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP